# Generated by Django 4.1.7 on 2023-04-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("typingtest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieScene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("transcript", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Conversation",
        ),
        migrations.DeleteModel(
            name="Movie",
        ),
    ]
