# Generated by Django 4.1.7 on 2023-04-11 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("typingtest", "0002_moviescene_delete_conversation_delete_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviescene",
            name="movie_file",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="movies/"
            ),
            preserve_default=False,
        ),
    ]
