# Generated by Django 4.1.7 on 2023-04-14 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('typingtest', '0003_moviescene_movie_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviescene',
            name='movie_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
