# Generated by Django 4.1.7 on 2023-04-15 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('typingtest', '0004_moviescene_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviescene',
            name='movie_audio',
            field=models.FileField(default=django.utils.timezone.now, upload_to='audio/'),
            preserve_default=False,
        ),
    ]
