# Generated by Django 4.1.7 on 2023-04-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingtest', '0006_remove_moviescene_movie_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviescene',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='thumbnail/'),
        ),
    ]
