# Generated by Django 4.1.7 on 2023-04-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("typingtest", "0008_alter_moviescene_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("score", models.FloatField()),
            ],
        ),
    ]
