# Generated by Django 4.1.7 on 2023-05-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("typingtest", "0009_userscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviescene",
            name="transcript_ai",
            field=models.TextField(blank=True, null=True),
        ),
    ]
