# Generated by Django 4.1.7 on 2023-05-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("typingtest", "0010_moviescene_transcript_ai"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviescene",
            name="audio_file",
            field=models.FileField(default=None, upload_to="audios/"),
            preserve_default=False,
        ),
    ]
